// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8aOx3dahdq8hd2lqWzB9dZ9f-zbwtb-g',
    appId: '1:518566059595:web:c4351a0d3f4fbc626377ce',
    messagingSenderId: '518566059595',
    projectId: 'smart-space-app-a9bb3',
    authDomain: 'smart-space-app-a9bb3.firebaseapp.com',
    storageBucket: 'smart-space-app-a9bb3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcQ5lbV8Z4K2eetVL7yWcQr-pwpNXsCcg',
    appId: '1:518566059595:android:a64ec9fd9fc5ef6f6377ce',
    messagingSenderId: '518566059595',
    projectId: 'smart-space-app-a9bb3',
    storageBucket: 'smart-space-app-a9bb3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQXKFFNKjQdD6ROQROAE4EI6ewxR6-ARA',
    appId: '1:518566059595:ios:c689392d1a0f51656377ce',
    messagingSenderId: '518566059595',
    projectId: 'smart-space-app-a9bb3',
    storageBucket: 'smart-space-app-a9bb3.firebasestorage.app',
    iosBundleId: 'com.example.smartSpaceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQXKFFNKjQdD6ROQROAE4EI6ewxR6-ARA',
    appId: '1:518566059595:ios:c689392d1a0f51656377ce',
    messagingSenderId: '518566059595',
    projectId: 'smart-space-app-a9bb3',
    storageBucket: 'smart-space-app-a9bb3.firebasestorage.app',
    iosBundleId: 'com.example.smartSpaceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8aOx3dahdq8hd2lqWzB9dZ9f-zbwtb-g',
    appId: '1:518566059595:web:2ca67bc988c4d4896377ce',
    messagingSenderId: '518566059595',
    projectId: 'smart-space-app-a9bb3',
    authDomain: 'smart-space-app-a9bb3.firebaseapp.com',
    storageBucket: 'smart-space-app-a9bb3.firebasestorage.app',
  );
}
